service: chatbot-lex

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handlers/health.hello
    events:
      - httpApi:
          path: /
          method: get

  lex:
    handler: handlers/lex.lex
    timeout: 300
    events:
      - httpApi:
          path: /
          method: post

  twilio:
    handler: handlers/twilio.twilio
    timeout: 45
    events:
      - httpApi:
          path: /twilio
          method: post


plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    fileName: requirements.txt
